[mgr]
append_keymap = [
  { on = [ "<Esc>" ], run = "escape", desc = "Exit visual mode, clear selected, or cancel search" },
  { on = [ "g", "d" ], run = "cd ~/Downloads", desc = "Go to Downloads" },
  { on = [ "g", "v" ], run = "cd ~/.config/nvim", desc = "Go to Neovim config" },
  { on = [ "g", "/" ], run = "cd ~", desc = "go home" },
  { on = [ "g", "m" ], run = "cd ~/demo", desc = "go demo" },
  { on = [ "<C-r>" ], run = "select --state=none", desc = "取消全选" },

  { on = [ "J" ], run = "steps 5", desc = "go demo" },
  { on = [ "K" ], run = "steps -5", desc = "go demo" }

  # # 模糊搜索增强
  # { on = [ "<C-f>" ], run = "find --smart", desc = "Smart find" },
  # { on = [ "<C-g>" ], run = "find --previous", desc = "Find previous" }
]

[input]
append_keymap = [
  { on = [
    "u"
  ], run = "undo", desc = "撤销上一个操作" },
  { on = [
    "<C-r>"
  ], run = "redo", desc = "重做操作" }
]
