[mgr]
cwd = { fg = "cyan" }

# Hovered
hovered         = { fg = "black", bg = "lightblue" }
preview_hovered = { underline = true }

# Find
find_keyword  = { fg = "yellow", italic = true }
find_position = { fg = "magenta", bg = "darkgray", italic = true }

# Marker
marker_selected = { fg = "lightgreen", bg = "lightgreen" }
marker_copied   = { fg = "lightyellow", bg = "lightyellow" }
marker_cut      = { fg = "lightred", bg = "lightred" }

# Tab
tab_active   = { fg = "lightblue" }
tab_inactive = { fg = "darkgray" }
tab_width    = 1

# Border
border_symbol = "│"
border_style  = { fg = "darkgray" }

# Highlighting
syntect_theme = ""

[status]
separator_open  = ""
separator_close = ""
separator_style = { fg = "darkgray", bg = "darkgray" }

# Mode
mode_normal = { fg = "black", bg = "lightblue", bold = true }
mode_select = { fg = "black", bg = "lightgreen", bold = true }
mode_unset  = { fg = "black", bg = "lightmagenta", bold = true }

# Progress
progress_label  = { bold = true }
progress_normal = { fg = "blue", bg = "black" }
progress_error  = { fg = "red", bg = "black" }

# Permissions
permissions_t = { fg = "lightgreen" }
permissions_r = { fg = "lightyellow" }
permissions_w = { fg = "lightred" }
permissions_x = { fg = "lightcyan" }
permissions_s = { fg = "darkgray" }
