# ln -s  ~/.config/nvim/yazi ~/.config/yazi 

[mgr]
# 排序方式：alphabetical, natural, modified, created, extension, size
sort_by = "alphabetical"
sort_sensitive = false
sort_reverse = false
sort_dir_first = true
linemode = "none"
show_hidden = false
show_symlink = true

[preview]
# 预览窗口设置
tab_size = 2
max_width = 600
max_height = 900
cache_dir = ""

[opener]
# 文件打开程序配置
edit = [
  { run = 'nvim "$@"', desc = "Edit with Neovim", block = true },
  { run = 'code "$@"', desc = "Edit with VS Code" },
]
open = [ { run = 'open "$@"', desc = "Open" } ]
reveal = [ { run = 'open -R "$@"', desc = "Reveal in Finder" } ]

[open]
# 文件类型关联
rules = [
  { name = "*/", use = "open" },
  { mime = "text/*", use = "edit" },
  { mime = "image/*", use = "open" },
  { mime = "video/*", use = "open" },
  { mime = "audio/*", use = "open" },
  { mime = "inode/x-empty", use = "edit" },
]
